example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

# TODO: Implement Routings Here

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import *

urlpatterns = [
    path('html', show_html, name='show_html'),
    path('xml', show_xml, name='show_xml'),
    path('json', show_json, name='show_json'),
    path('', show, name='show')
    ]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('update/<int:id>', update_task, name='update-task'),
    path('delete/<int:id>', delete_task, name='delete-task'),
    path('json', get_todolist_json, name='get_todolist_json'),
    path('add', add_todolist, name='add_todolist')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchList(models.Model):
    watched = models.CharField(max_length=5)              # sudah/belum
    title = models.CharField(max_length=200)
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Task

class NewTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):

    data_katalog = CatalogItem.objects.all()

    context = {
        'list_katalog': data_katalog,
        'nama': 'Muhammad Falensi Azmi',
        'npm': '2106630334',
    }

    return render(request, "katalog.html", context)

# TODO: Create your views here.

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

def show_html(request):
    data = MyWatchList.objects.all()
    sudah = MyWatchList.objects.filter(watched='Sudah').count()
    belum = MyWatchList.objects.filter(watched='Belum').count()

    if sudah >= belum:
        msg = "Selamat, kamu sudah banyak menonton!"
    else:
        msg = "Wah, kamu masih sedikit menonton!"

    context = {
        'list_watchlist': data,
        'msg':msg
    }

    return render(request, 'mywatchlist.html', context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show(request):
    return HttpResponse("Halaman MyWatchList")

todolist/views.py
import datetime
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from todolist.forms import NewTaskForm
from todolist.models import Task
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    form = NewTaskForm
    context = {
        'user': request.user.username,
        'last_login': request.COOKIES['last_login'],
        'form':form
    }
    return render(request, 'todolist.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = NewTaskForm

    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            messages.success(request, 'Berhasil menambahkan task!')
            return redirect('todolist:show_todolist')

    context = {'form':form}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
def update_task(request, id):
    if request.method == "POST":
        data = Task.objects.get(id=id)
        if data.is_finished == False:
            data.is_finished = True
        else:
            data.is_finished = False
        data.save()
        return redirect('todolist:show_todolist')
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_task(request, id):
    if request.method == "POST":
        data = Task.objects.get(id=id)
        data.delete()
        return redirect('todolist:show_todolist')
    return redirect('todolist:show_todolist')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form':form}
    return render(request, 'register.html', context)  

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def get_todolist_json(request):
    data = Task.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def add_todolist(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        desc = request.POST.get("description")
        user = request.user

        new_task = Task(title=title, description=desc, user=user)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

# def delete_ajax(request):
#     if request.method == "POST":
#         id = request.POST.get("id")
#         print(id)
#         data = Task.objects.get(id=id)
#         data.delete()
#         return HttpResponse(b"DELETED", status=204)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 2 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_katalog %}
    <tr>
      <th>{{item.item_name}}</th>
      <th>{{item.item_price}}</th>
      <th>{{item.item_stock}}</th>
      <th>{{item.rating}}</th>
      <th>{{item.description}}</th>
      <th>{{item.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Muhammad Falensi Azmi</p>

  <h5>Student ID: </h5>
  <p>2106630334</p>

  <br>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_watchlist %}
    <tr>
      <th>{{item.watched}}</th>
      <th>{{item.title}}</th>
      <th>{{item.rating}}</th>
      <th>{{item.release_date}}</th>
      <th>{{item.review}}</th>
    </tr>
    {% endfor %}
  </table>

  <br><br>
  
  {{msg}}

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Muhammad Falensi Azmi</p>

  <h5>Student ID: </h5>
  <p>2106630334</p>

  <br>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_watchlist %}
    <tr>
      <th>{{item.watched}}</th>
      <th>{{item.title}}</th>
      <th>{{item.rating}}</th>
      <th>{{item.release_date}}</th>
      <th>{{item.review}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Pembuatan Task Baru</title>
{% endblock meta %}

{% block content %}

<div class="mt-5 col-md-8 mx-auto container">
    <h1 class="text-gray mb-5">Task Baru</h1>  
    <form method="POST" >  
        {% csrf_token %}  
        <table class="table table-striped table-bordered table-hover">  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input type="submit" name="submit" class="btn btn-primary"></td>  
            </tr>  
        </table>  
    </form>
    <h5 class="mt-5">
        <a href="{% url 'todolist:show_todolist' %}">Kembali</a>
    </h5>
</div>


{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login container">
    
    <div class="mt-5 col-md-8 mx-auto">
        <h1 class="text-gray mb-5">Login</h1>  
        <form method="POST" action="">
            {% csrf_token %}
            <table class="table table-striped table-bordered table-hover">
                <tr>
                    <td class="fw-bold">Username: </td>
                    <td><input type="text" name="username" placeholder="Username"></td>
                </tr>
                        
                <tr>
                    <td class="fw-bold">Password: </td>
                    <td><input type="password" name="password" placeholder="Password"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input type="submit" value="Login" class="btn btn-primary"></td>
                </tr>
            </table>
        </form>
        
        <h5 class="mt-5">
            Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
        </h5>

        {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}     
    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login container">

    <div class="mt-5 col-md-8 mx-auto">
        <h1 class="text-gray mb-5">Formulir Registrasi</h1>  
        <form method="POST">
            {% csrf_token %}  
            <table class="table table-striped table-bordered table-hover">
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar" class="btn btn-primary"></td>  
                </tr>
            </table>  
        </form>

        <h5 class="mt-5">
            Sudah punya akun? <a href="{% url 'todolist:login' %}">Login Disini</a>
        </h5>

        {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
        {% endif %}
    </div>
</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<style>
.card:hover{
  background-color: lightgray;
}
</style>
{% endblock meta %}

{% block content %}

<div class="mt-5 col-md-10 mx-auto container">
  <h1>Tugas 4 PBP/PBD</h1>

  <br>

  <h2>Name: </h5>
  <p>Muhammad Falensi Azmi</p>

  <h2>Student ID: </h5>
  <p>2106630334</p>

  <br><br><br>

  <p>Logged in as: {{user}}</p>

  <div class="gap-2">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Tambah Task
    </button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Task Baru</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="mt-5 mx-auto container">
              <form method="POST" id="create_form" onsubmit="return false;">
                  {% csrf_token %}  
                  <table class="table table-striped table-bordered table-hover">  
                    {{ form.as_table }}  
                    <td></td>
                    <td><input type="submit" name="submit" class="btn btn-primary" id="tombol_submit" data-bs-dismiss="modal"></td> 
                  </table>  
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <a href="{% url 'todolist:logout' %}" class="btn btn-danger">Logout</a>

  </div>

  <br><br>
  
  <div class="row row-cols-auto g-4" id="myrow">
  </div>

  <br><br>

  <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>

<script>
  async function getTodolist() {
    return fetch("json").then((res) => res.json())
  }

  async function refreshTodolist() {
        document.getElementById("myrow").innerHTML = ""
        const todolist = await getTodolist()
        let htmlString = ''
        todolist.forEach((item) => {
          htmlString += `
          <div class="col">
          <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://www.computerhope.com/jargon/t/task.png" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">${item.fields.title}</h5>
            <p class="card-text">${item.fields.description}</p>
            <p class="card-text">Selesai: ${item.fields.is_finished}</p>
            
            <div class="d-grid gap-2">
              <form action="/todolist/update/${item.pk}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Ubah" class="btn btn-primary">
              </form>
              <form method="POST" onsubmit="return false;">
                <input type="submit" value="Hapus" class="btn btn-danger" onclick="deleteTodolist(${item.pk})">
              </form>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">Ditambahkan pada: ${item.fields.date}</small>
          </div>
        </div>
      </div>
          `
        })
        document.getElementById("myrow").innerHTML = htmlString
  }

  function addTodolist() {
    fetch("add", {
          method: "POST",
          body: new FormData(document.querySelector('#create_form'))
      }).then(refreshTodolist)
    return false
  }

  function deleteTodolist(id) {
    fetch("delete/"+id, {
          method: "POST",
      }).then(refreshTodolist)
    return false
  }

  document.getElementById("tombol_submit").onclick = addTodolist;
  refreshTodolist()
</script>
{% endblock content %}